command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]

env:
  # Optional: pin a specific warehouse. If omitted, the app auto-discovers one.
  # - name: DATABRICKS_WAREHOUSE_ID
  #   value: "your-warehouse-id-here"
